# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
bioc_packages: multtest

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
